### PR TITLE
Drop dependency on tuple, allows to build with GHC-8.4.1

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by byorgey** [comment]
Thanks.  Currently blocked on https://github.com/haskell-fswatch/hfsnotify/pull/77 .

**Comment by phadej** [comment]
@byorgey there are install plans with GHC-8.4.1 and `hinotify-0.3.8.1` - if you don't insist on picking latest versions.

deps

**Comment by byorgey** [comment]
Oh, so there are.  Maybe earlier when I was testing it there was something else that hadn't updated yet.  Anyway, I will upload once I make sure everything builds.

**Comment by phadej** [comment]
@byorgey great, thanks!

**Comment by phadej** [comment]
Edit: that's using the `master` versions of  `diagrams  diagrams-contrib  diagrams-core  diagrams-lib  diagrams-svg	  dual-tree	svg-builder  SVGFonts`

**Comment by byorgey** [comment]
Right, I've been going through and updating dependencies on Hackage.

**Pull request merged**
